var prompts = [
"What was your favorite mundane moment of the day?",
"What was the best thing you've eaten this week?",
"What, in your home, are you gareful for?",
"How have you grown in the last year?",
"What makes you laugh so hard your face hurts?",
"What is the nicest thing a stranger ever did for you or said to you?",
"What are some ways you could explore better self-care?",
"What would be the best extinct animal to own as a pet, assuming it could be tamed and would be happy and healthy in your home?",
"Who is your favorite fictional charater and why?",
"How do your peers describe you? How do you *want* your peers to describe you?",
"If you could build a perfect custome home, what would it have? Where would you build it?",
"What do you wish you were doing more of? How can you do more of it?",
"What is your strongest personality trait?",
"Where do you see yourself in three years? What steps are you taking to get there?",
"Write about a moment that was terrible when it happened, but through cause-and-effect, resulted in something good happening.",
"Write about the earliest clear memory you have.",
"Compliment a stranger today. What did you say? How did they respond?",
"What impact do you want your existence to have on humanity?",
"What is stressing you out right now? What people and resources could you lean on for support?",
"What is the absolute core of your ethos? What do you stand for?",
"What is your take on romantic love?",
"What is your take on platonic love?",
"What traits do you find physically beautiful in other people?",
"What was your most precious toy when you were a child?",
"What are the characteristics you seek out in friendship? In working relationships?",
"Why do you live where you do?",
"What is something about your living space that you don't like, but that you have the power to change? How can you make this change more feasible?",
"How would you dress if all clothing was comfortable, nobody judged, and the only thing that mattered was that you like it?",
"Write a letter to your ten-year-old self.",
"How has your health been? What can you do today to take care of your body?",
"You have won a month-long, paid, all-expenses-covered vacation to anywhere in the world! Where are you going? What will you do?",
"If you had enough passive income to comfortably retire right now, with no major changes to your lifestyle, what would you do?",
"What is a skill you want to work on? How can you grow in this way?",
"What is a hobby you're curious about exploring?",
"Give your inner critic, anxiety, depression, or other internal challenges a stupid name. Imagine it talking like a bratty child or publicly-intoxicated uncle. Now, write a short monologue from its perspective, as if it were writing a letter. How would you write back to a real person talking to you this way?",
"What are you putting up with that you shouldn't be?",
"Write something you wish someone would say to you.",
"What was a huge, pivotal change in your life? If your life were a novel, what were some earlier foreshadowings of this event?",
"When was the last time you were afraid? In retrospect, was the danger real? How would you react if you were in this situation again?",
"Who are you, outside of the roles you play?",
"Who are you behind closed doors? What are you doing when nobody's watching, or when you're most free?",
"Write a letter to your parents (or whoever was most instrumental in raising you), to be given to them shortly before you are born. What advice would you give them?",
"Where did you notice beauty in the world today?",
"What is the meaning and origin of your first name? What does that mean to you?",
"What is the meaning and origin of your family name? What does that mean to you?",
"What is your sun sign, and what traits are commonly associated with it? Regardless of your belief in astrology, do you identify with any of these traits?",
"What is something you're embarassed of liking? Why?",
"What piece of media had the greatest influence on you as a child?",
"You have to share a cramped apartment with one relative for a month. Who do you chose and why?",
"When asked to scale pain from one to ten, what is your reference point for one? Five? Ten? What was the worst physical pain you have ever experienced?",
"What is your favorite holiday and why?",
"Your birthday is now a holiday, dedicated to whatever you want. Name the holiday, describe what it stands for, and list the festivities.",
"If you're partnered, describe your favorite little things you've noticed about them since you've met. If you're single, describe the personality of your ideal partner.",
"What was something that scared you as a child that turned out to not be a real threat?",
"What are you saving up for?",
"When was the last time you tried a new food?",
"What's something little that's given you joy recently?",
"What have you learned recently?",
"What is a constructive goal you've set for yourself? How will you reward yourself when you reach it?",
"Who is your idol and why? What do they do that makes you look up to them?",
"How much thought have you given your gender? What does feminimity/masculinity/androgyny entail to you? Do you feel freedom exploring these, or do you feel constraint?",
"How much thought have you given your political alignment? What kind of future do you want to build? What can you do to make a difference?",
"What was the most disgusting food you've ever eaten? Would you eat it again for money? What's your price?",
"Write a short CV for your pet, applying to take your current job. If you have no pets, use any animal you've met in the past.",
"Got any tattoos? Talk about them! If you have no tattoos, is there a reason? Do you have an equivalent way of expressing yourself?",
"What's your aesthetic right now?",
"Do you dream often? What is the strangest dream you've ever had? Do you think it had meaning?",
"What is your favorite joke to tell? (Does this earn laughs or groans?",
"Imagine you're a robot or animal. Write a ''maintenence guide'' on how to keep you alive and running.",
"What does world peace look like to you?",
"If you were the most powerful & wealthy person on the planet, what would you do?",
"If your name were an acronym, what would it stand for?",
"What do you do on rainy days?",
"What is your dream job?",
"What is your favorite quote? What does it mean to you?",
"What is your favorite type of food? What do you love about it?",
"What is your favorite art form to enjoy? To create?",
"Would you call yourself an artist? Why or why not?",
"What is something you love about your body?",
"If you could shape-shift, but only within the realm of natural human variation, what would you chose to look like?",
"Observe a stranger today. Give them a name, and write a short backstory for them.",
"What does success look like to you?",
"Do you believe in the supernatural? If so, what about it compells you? If not, what would it take to convince you?",
"Are you religious? How does your belief system impact your day-to-day life?",
"Think about your favorite flower. Look up its meaning in the Victorian language of flowers (or other symbology if it is absent from that dictionary) and write it here. What does this flower mean to you now?",
"What is your favorite living animal? Your favorite extinct animal? If they were in a room together, what would happen?",
"Does pineapple belong on pizza? How stromgly do you feel about this?",
"What is the best food item you make? What's the recipe?",
"What unanswered question about our universe or history would you want to find the answer to?",
"What activists in ages past helped you have the rights you have today?",
"What is your disaster plan in the event of a natural disaster? A medical emergency?",
"Think of some food pairs that taste great alone but would be terrible together.",
"What is your least favorite color? Your favorite color? How do they look next to each other?",
"Make up an invention that would change the world.",
"You get a million dollars if you can perfectly nail a song at a kareoke bar. What song do you pick, and what do you do with the money?",
"What is your desktop background image right now? Why?",
"What's a weird fact you know?",
"What is your most-used emoji? Give an example of how you typically use it.",
"What is your pet's name? Now...what are all the things you call them that are NOT their name?",
"What would be the single best superpower and why?",
"If you were a superhero, what would your power and weakness be?",
"How do you handle feedback? When was the last time someone gave you feedback? Did you use it?",
"What is your favorite lunch?",
"What was your first job? Did you like it? Why did you leave?",
"What toppings do you put on your burger, assuming a 'burger' consists only of a bun and patty to start with?",
"What was your favorite subject in school? Your least favorite?",
"What is the worst advice you have ever been given?",
"You got roped into a date with someone you really don't like. You're at a casual restaraunt. What is something you could say or do as soon as they sat down to make them stand back up and leave?",
"Have you ever been told you look like a particular animal? A celebrity? A different name?",
"What is your favorite scent?",
"What would you title your autobiography? Does the title come from something?",
"When you were little, what did you want to be when you grew up? List as many as you can remember, in chronological order from youngest to oldest.",
"What is the best city in your state? The worst? If each of those cities were a person, who would win in a fight?",
"What's the most out-of-character thing you've ever done?",
"You have an unlimited supply of one thing for life. It can't be money, and these things can't be sold. What is it and why?",
"If you could instantly become an expert in something, what would it be?",
"If you could arrange a fight between any two fictional charaters, who would you want to see duking it out? Who do you think would win?",
"Do you like your parents? Why or why not?",
"Make up a degree that, by some technicality, you would somehow qualify to have.",
"Write a corporate-sounding letter from the perspective of your pet issuing a complaint to you.",
"What are you so bad at that it's funny?",
"What is something almost completely useless that you are weirdly good at?",
"What do you currently have in your pockets?",
"You overhear someone asking a friend or family member what kind of person you are. What do you hope they say?",
"What are you usually doing when you look at the clock and think, ''it's already been an hour!?'' Is it something you like doing, or something you want to change?",


];